### ISSUE TITLE
Staff page "Read my blogs" links do not work

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#319]
Hiya! First some facts, followed by a request. 

1. If I click the "Read my blogs" links on the team page, I get a 404 image.
2. The links were set up on staging as https://akvo.org/author/lindaleunissen/ and were supposed to display like the search results page
3. Instead I found a working link that is https://akvo.org/blog/author/lindaleunissen/ which displays like a blog overview page. 

@designbychris I actually like how the overview looks in the second URL. Can you tweak that page a little bit and we keep it? Remove the header image, instead have an extra-narrow coloured background in Green HEX 03AD8C

@designbychris @samvthom16 Is there an automatic way to update to the correct URL's so we don't have to change the link manually for each person on the staff list?

Thanks! L

**Comment by designbychris** [comment]
@samvthom16 can you check the link issue.

@Lindaleunissen I have fixed the header to be smaller and with the green background. Please refresh and take a look see :)

**Comment by samvthom16** [comment]
@Lindaleunissen these links are stored in the DB and not generated automatically, which means that they would have to be updated manually.

**Comment by designbychris** [comment]
This seems to all be ok now

**Comment by Lindaleunissen** [comment]
Read my blogs links on the staff page are still not working.

**Comment by designbychris** [comment]
@samvthom16 not sure whats happened. Has someone updated the Permalinks?

**Comment by samvthom16** [comment]
@designbychris no updation has been done on the permalinks

**Comment by samvthom16** [comment]
@designbychris @Lindaleunissen the links from the custom fields needs to be updated manually. I can see that only some of them have been updated.

**Comment by designbychris** [comment]
Ahhhh yes, thanks @samvthom16 I forgot we did that! @Lindaleunissen this still needs to be done for all the others with blogs. You will need to check against the ones that work and those that don't :)

I hope that helps?

**Comment by Lindaleunissen** [comment]
I'm looking at the staff section of the page, and cannot see where I should update the url?

**Comment by designbychris** [comment]
@Lindaleunissen its within the Akvo Staff, see this: https://akvo.org/wp-admin/post.php?post=52046&action=edit

**Comment by Lindaleunissen** [comment]
Thanks! On it :)
